In [2]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [4]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [5]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [6]:
matriz = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(matriz)
matriz.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

### Agregar o Eliminar dimensiones

In [7]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [8]:
comparative = np.array([1,2,3])
print(comparative,'<---- | result without expand | n. of dimensions:',comparative.ndim)


expand = np.expand_dims(np.array([1,2,3]), axis=1)
print(expand,'<-- | result of expand | n. of dimensions:',expand.ndim)

[1 2 3] <---- | result without expand | n. of dimensions: 1
[[1]
 [2]
 [3]] <-- | result of expand | n. of dimensions: 2


In [9]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


### Reto
- Hacer un tensor de 5 dimensiones
- Sumarle una dimension
- Eliminar las dimensiones que no se estan usando

In [14]:
tensor = np.array([[1,2,3],[11,22,33],[111,222,333]], ndmin=5)
print(tensor,'Numero de dimensiones:',tensor.ndim)

[[[[[  1   2   3]
    [ 11  22  33]
    [111 222 333]]]]] Numero de dimensiones: 5


In [11]:
tensor = np.expand_dims(tensor, axis=1)

print(tensor,'Numero de dimensiones:',tensor.ndim)


[[[  1   2   3]]

 [[ 11  22  33]]

 [[111 222 333]]] Numero de dimensiones: 3


In [12]:
tensor = np.squeeze(tensor)
print(tensor,'Numero de dimensiones:',tensor.ndim)


[[  1   2   3]
 [ 11  22  33]
 [111 222 333]] Numero de dimensiones: 2
