In [6]:
import numpy as np

### Condiciones

#### Array

Creamos un array del 1 al 10 para trabajar con operaciones condicionales


In [9]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Guardamos uen una variable una lista booleana con verdaderos y falsos segun la condicion y el array anterior

In [15]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Usamos la lista booleana para filtrar los valores verdaderos de la condicion

In [19]:
print(f"""
arr[indices_cond]: {arr[indices_cond]}

es igual a

arr[(arr > 5)]: {arr[(arr > 5)]}
""")


arr[indices_cond]: [ 6  7  8  9 10]

es igual a

arr[(arr > 5)]: [ 6  7  8  9 10]



Multiples Condiciones

In [21]:
arr[(arr > 5) & (arr < 9)]


array([6, 7, 8], dtype=int8)

In [22]:
arr[(arr > 5)] = 99

In [24]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [25]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

#### Matriz

In [29]:
matriz = np.random.randint(10, size=(3,3))
matriz

array([[4, 9, 1],
       [2, 8, 7],
       [7, 0, 0]])

Condiciones con Matriz

np.where(condicion, valor True, valor False)

In [34]:
np.where(matriz > 5, True, False)

array([[False,  True, False],
       [False,  True,  True],
       [ True, False, False]])