In [1]:
import numpy as np

In [6]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### Creando Arrays
#### Indice de Arrays 
- 1 ✅ np.arange (Start,Ens,Steps) → es como el list( range(0,10)) pero como arrange
- 2 ✅ np.zeros(n)
- 3 ✅ np.ones(n)
- 4 ✅ np.linspace(Start, End, Cant n de Start a End)
- 5 ✅ np.eye(n) ·· Matriz identidad
- 6 ✅ np.random.rand(Columnas, Filas, mas dimensiones ) ·· Ambos con numeros randoms
- 7 ✅ np.random.randint(Start, End, Dimensiones) ·· N random entre Start y End y tupla dims
- 8 ✅ np.full((row, column), n) 

##### Vector

In [15]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##### Matriz de valor 0

In [28]:
np.zeros(np.array([3,3]), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

##### Matriz de valor 1

In [81]:
np.ones(np.array([3,3]), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##### Matriz de distribucion normal estandar

In [48]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

##### Matriz identidad 👇

In [67]:
np.eye(4,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

##### Numero random entre el 0 y el 1

In [74]:
np.random.rand(4,4)

array([[0.97322336, 0.81379656, 0.18764553, 0.77100954],
       [0.42398484, 0.4949759 , 0.6915872 , 0.68222531],
       [0.59287831, 0.84433688, 0.79783557, 0.13253752],
       [0.00597543, 0.09904712, 0.5983025 , 0.65308088]])

##### Vector de numeros enteros aleatorio

In [78]:
np.random.randint(1,15,4)

array([ 8,  2, 12, 11])

##### Matriz de numeros enteros aleatorios

In [80]:
np.random.randint(1,100,(5,5))


array([[52,  7, 59, 57, 96],
       [34, 25, 19,  5, 68],
       [80, 66, 43, 74, 31],
       [48, 72, 28, 86, 87],
       [90, 96, 60, 29, 15]])

##### Matriz de un numero predeterminado



In [86]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])