In [2]:
import numpy as np

In [25]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [26]:
arr = np.array([1,2,3,4], dtype="float64")
arr.dtype

dtype('float64')

In [28]:
arr

array([1., 2., 3., 4.])

In [35]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr

array([0., 1., 1., 1., 1.], dtype=float16)

In [37]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [47]:
arr = np.array(['1.1','1','2','3'])
arr = arr.astype(np.float16)
arr

array([1.1, 1. , 2. , 3. ], dtype=float16)

In [49]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])