In [1]:
import numpy as np

#### Shapre & Reshape

In [2]:
arr = np.random.randint(1,10,(3,2))
arr

array([[7, 3],
       [2, 1],
       [9, 6]])

##### Shape

In [3]:
arr.shape

(3, 2)

In [4]:
arr

array([[7, 3],
       [2, 1],
       [9, 6]])

In [5]:
#### Reshape

In [6]:
arr.reshape(1,6)

array([[7, 3, 2, 1, 9, 6]])

In [7]:
arr.reshape(2,3)

array([[7, 3, 2],
       [1, 9, 6]])

In [8]:
np.reshape(arr,(1,6))

array([[7, 3, 2, 1, 9, 6]])

In [9]:
arr

array([[7, 3],
       [2, 1],
       [9, 6]])

##### Ordenar el array como lo harias con el lenguaje C

In [10]:
np.reshape(arr,(2,3), 'C')

array([[7, 3, 2],
       [1, 9, 6]])

##### Ordenar el array como lo harias con el lenguaje Fortran

In [11]:
np.reshape(arr,(2,3), 'F')


array([[7, 9, 1],
       [2, 3, 6]])

##### Ordenar el array como lo esta optimizado el sistema

In [12]:
np.reshape(arr,(2,3), 'A')


array([[7, 3, 2],
       [1, 9, 6]])

#### Reto
- 1 Crear un tensor / array con cualq dimensionalidad
- 2 Intercambiar valores de array
- 3 Crear un valor que no respete los valores originales

##### Creamos un tensor 4D

In [13]:
a = np.random.randint(0,10, (1,2,3,2))
print(a.ndim)
a

4


array([[[[8, 4],
         [2, 6],
         [5, 8]],

        [[3, 6],
         [5, 2],
         [1, 5]]]])

In [14]:
a.shape

(1, 2, 3, 2)

##### Reordenar valores del tensor con C

In [15]:
a.reshape(3,1,1,4,order='C')

array([[[[8, 4, 2, 6]]],


       [[[5, 8, 3, 6]]],


       [[[5, 2, 1, 5]]]])

##### Reordenar valores del tensor con Fortran

In [16]:
a.reshape(1,1,1,12,order='F')


array([[[[8, 3, 2, 5, 5, 1, 4, 6, 6, 2, 8, 5]]]])

##### Reordenar con un valor que no se pueda

In [19]:
a.reshape(1,2,3,4)

ValueError: cannot reshape array of size 12 into shape (1,2,3,4)