In [2]:
import numpy as np

# Operaciones

## Multiplicacion de lista con Python Vainilla

In [6]:
lista = [1,2]
lista

[1, 2]

In [10]:
lista * 2

[1, 2, 1, 2]

In [14]:
arr = np.arange(0,10)
arr2 = arr.copy()

## Multiplicacion de lista con Numpy

### Operaciones Armiticas

#### Array

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
1 / arr

/tmp/ipykernel_1030/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [23]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#### Matriz

In [38]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [40]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
print(f"""
+ {matriz + matriz2} 

- {matriz - matriz2}

* {matriz * matriz2}

/ {matriz / matriz2}
""")



+ [[ 0  2  4  6  8]
 [10 12 14 16 18]] 

- [[0 0 0 0 0]
 [0 0 0 0 0]]

* [[ 0  1  4  9 16]
 [25 36 49 64 81]]

/ [[nan  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]



/tmp/ipykernel_1030/3097488195.py:8: RuntimeWarning: invalid value encountered in true_divide
  / {matriz / matriz2}


Producto Punto

In [58]:
print(f"""
{matriz}   

{matriz2.T}""")


[[0 1 2 3 4]
 [5 6 7 8 9]]   

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [59]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [61]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])