In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)

In [4]:
type(arr)

numpy.ndarray

In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[0]  + arr[5]

7

In [8]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
matriz[0,2]

3

In [10]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[-3:]

array([7, 8, 9])

In [13]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [15]:
a = np.zeros((2,3,4))
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]]])

In [17]:
a[0:2 ,  0 , ]

array([[1, 2, 3],
       [9, 8, 7]])