In [155]:
import numpy as np

### Funciones Principales con Numpy

Creamos un array de numeros aleatorios y una matriz del array creado

In [156]:
arr = np.random.randint(1,20,10)

In [157]:
matriz = arr.reshape(2,5)
matriz

array([[ 3,  7,  4, 15, 17],
       [10,  1,  4,  7, 19]])

In [158]:
arr

array([ 3,  7,  4, 15, 17, 10,  1,  4,  7, 19])

#### Encontrar el maximo valor

In [159]:
arr.max()

19

In [160]:
matriz

array([[ 3,  7,  4, 15, 17],
       [10,  1,  4,  7, 19]])

In [161]:
matriz.max()

19

##### Valor maximo de matriz por eje (Filas o Columnas)

matriz.max(0): Columnas

matriz.max(1): Filas

In [162]:
matriz

array([[ 3,  7,  4, 15, 17],
       [10,  1,  4,  7, 19]])

In [163]:
print("Maximo valor por eje de Columnas:",matriz.max(0))
print("Maximo valor por eje de Filas:",matriz.max(1))


Maximo valor por eje de Columnas: [10  7  4 15 19]
Maximo valor por eje de Filas: [17 19]


#### Indice del valor mas grande

##### Array

In [164]:
arr.argmax()

9

##### Matriz

In [165]:
print("Indice del maximo valor por eje de Columnas:",matriz.argmax(0))
print("Indice del maximo valor por eje de Filas:",matriz.argmax(1))


Indice del maximo valor por eje de Columnas: [1 0 0 0 1]
Indice del maximo valor por eje de Filas: [4 4]


In [166]:
matriz.argmax(1)


array([4, 4])

#### Encontrar el valor mas pequeno

##### Array

In [167]:
arr.min()

1

##### Matriz

In [168]:
print("Minimo por eje de Columnas:",matriz.min(0))
print("Minimo por eje de Filas:",matriz.min(1))


Minimo por eje de Columnas: [ 3  1  4  7 17]
Minimo por eje de Filas: [3 1]


In [169]:
matriz.min(1)

array([3, 1])

#### Indice del valor mas pequeno

##### Array

In [170]:
arr.argmin()

6

In [171]:
matriz

array([[ 3,  7,  4, 15, 17],
       [10,  1,  4,  7, 19]])

##### Matriz

In [172]:
print("Minimo por eje de Columnas:",matriz.min(0))
print("Minimo por eje de Filas:",matriz.min(1))


Minimo por eje de Columnas: [ 3  1  4  7 17]
Minimo por eje de Filas: [3 1]


In [173]:
matriz.min(1)

array([3, 1])

In [174]:
print("Indice del minimo valor por eje de Columnas:",matriz.argmin(0))
print("Indice del minimo valor por eje de Filas:",matriz.argmin(1))

Indice del minimo valor por eje de Columnas: [0 1 0 1 0]
Indice del minimo valor por eje de Filas: [0 1]


#### Espacios entre el pico mayor y el pico menor

##### Array

In [175]:
arr

array([ 3,  7,  4, 15, 17, 10,  1,  4,  7, 19])

In [176]:
print(f"""
Valor minimo del array: {arr.min()}
Valor maximo del array: {arr.max()}
Valor Peak to Peak del array: {arr.ptp()}
""")


Valor minimo del array: 1
Valor maximo del array: 19
Valor Peak to Peak del array: 18



##### Matriz

In [177]:
matriz

array([[ 3,  7,  4, 15, 17],
       [10,  1,  4,  7, 19]])

In [178]:
print(f"""
Valor maximo de columnas de la matriz: {matriz.max(0)}
Valor minimo de columnas de la matriz: {matriz.min(0)}
Valor Peak to Peak de columnas de la matriz: {matriz.ptp(0)}

Valor maximo de filas de la matriz: {matriz.max(1)}
Valor minimo de filas de la matriz: {matriz.min(1)}
Valor Peak to Peak de filas de la matriz: {matriz.ptp(1)}
""")



Valor maximo de columnas de la matriz: [10  7  4 15 19]
Valor minimo de columnas de la matriz: [ 3  1  4  7 17]
Valor Peak to Peak de columnas de la matriz: [7 6 0 8 2]

Valor maximo de filas de la matriz: [17 19]
Valor minimo de filas de la matriz: [3 1]
Valor Peak to Peak de filas de la matriz: [14 18]



#### Ordenar de menor a mayor

##### Array

In [179]:
arr.sort()
print('Array ordenado',arr)

Array ordenado [ 1  3  4  4  7  7 10 15 17 19]


#### Encontrar Percentiles

In [180]:
print('Valor del percentil   0%:',np.percentile(arr,0))
print('Valor del percentil  25%:',np.percentile(arr,25))
print('Valor del percentil  50%:',np.percentile(arr,50))
print('Valor del percentil  75%:',np.percentile(arr,75))
print('Valor del percentil 100%:',np.percentile(arr,100))


Valor del percentil   0%: 1.0
Valor del percentil  25%: 4.0
Valor del percentil  50%: 7.0
Valor del percentil  75%: 13.75
Valor del percentil 100%: 19.0


#### Encontrar Mediana

##### Array

In [181]:
print('Mediana de una Array:',np.median(arr))

Mediana de una Array: 7.0


##### Matriz

In [182]:
print('Mediana de una matriz por columnas:',np.median(matriz,0))
print('Mediana de una matriz por filas:',np.median(matriz,1))

Mediana de una matriz por columnas: [ 4.   6.5  9.5 10.5 13. ]
Mediana de una matriz por filas: [ 4. 15.]


#### Desviacion estandar

In [183]:
np.std(arr)

5.984145720150872

#### Varianza

In [184]:
np.var(arr)

35.81

#### Media

In [185]:
np.mean(arr)

8.7

#### Concatenate

In [192]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


##### Concatenación por columnas

In [194]:
np.c_[a,b]


array([[1, 2, 5],
       [3, 4, 6]])

##### Concatenación por filas

In [196]:
np.r_[a,[b]]
# b está con corchetes por que debe tener la misma dimensión que a



array([[1, 2],
       [3, 4],
       [5, 6]])

##### Concatenacion Manual

In [187]:
print(f"""
Dimensiones de a: {a.ndim}
Dimensiones de b: {b.ndim}
""")


Dimensiones de a: 2
Dimensiones de b: 1



In [198]:
b = np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [199]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [200]:
c = np.concatenate((a,b.T), axis=1)
c
# La T delante de b es la transpuesta

array([[1, 2, 5],
       [3, 4, 6]])